name: CI Python Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest mypy isort
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run isort (organize imports)
        run: isort .

      - name: Commit isort changes (if any)
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --cached --quiet || git commit -m "style: auto-format imports with isort"

      - name: Push isort changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Run mypy (type checking)
        run: mypy . --explicit-package-bases --ignore-missing-imports

      - name: Run pytest (if tests exist)
        run: |
          if [ -d tests ] || [ -d test ]; then python -m pytest; else echo "No test folder found, skipping tests."; fi
